### ISSUE TITLE
The original author's name is Damian Wildie not David Wildie.

### ISSUE THREAD

**Issue by dwildie** [rosco-m68k/cpm68k#4]
The original author's name is Damian Wildie not David Wildie.

**Comment by harrowm** [comment]
Apologies, we will fix this!

**Comment by harrowm** [comment]
Done!

**Comment by dwildie** [comment]
Thank you






---- On Thu, 11 Aug 2022 10:46:48 +1000 Malcolm Harrow ***@***.***> wrote ---





Apologies, we will fix this!

**Comment by dwildie** [comment]
You missed the other instance of "David Wildie"

**Comment by harrowm** [comment]
Apologies.  Missed this while editing on the phone.  Now corrected.  If you would like to play around with a Rosco card then message me at Harrow dot Malcolm at gmail dot com and I’ll send you a working card.
